add_newline = false
[line_break]
disabled = true

[git_branch]
symbol = " "
# symbol = "🌱 "

[aws]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[golang]
disabled = true

[git_status]
disabled = true
