add_newline = false
[line_break]
disabled = true

[git_branch]
symbol = " "

[aws]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[golang]
disabled = true

[git_status]
disabled = true

[kubernetes]
format = '[$context \($namespace\)](dimmed blue) '
disabled = false
detect_folders = ["kubernetes"] # there is a kubernetes folder in pocus
